import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import guestsRouter from "./guests";
import preregistrationsRouter from "./preregistrations";
import watchlistRouter from "./watchlist";
import auditRouter from "./audit";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import productionsRouter from "./productions";
import photosRouter from "./photos";
import studiosRouter from "./studios";
import alertsRouter from "./alerts";
import knownGuestsRouter from "./known-guests";
import kioskRouter from "./kiosk";
import clientRouter from "./client";
import settingsRouter from "./settings";
import scanSessionsRouter from "./scan-sessions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(guestsRouter);
router.use(preregistrationsRouter);
router.use(watchlistRouter);
router.use(auditRouter);
router.use(usersRouter);
router.use(dashboardRouter);
router.use(productionsRouter);
router.use(photosRouter);
router.use(studiosRouter);
router.use(alertsRouter);
router.use(knownGuestsRouter);
router.use(kioskRouter);
router.use(clientRouter);
router.use(settingsRouter);
router.use(scanSessionsRouter);

export default router;
